name: mosques_teacher
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  go_router: ^17.1.0
  dio: ^5.9.1
  animated_snack_bar: ^0.4.0
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^10.0.0
  google_fonts: ^8.0.1
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon-logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/

flutter_gen:
  output: lib/gen/
  line_length: 120

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo.png
